# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acasper <acasper@student.42berlin.de>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/01/19 17:17:51 by acasper           #+#    #+#              #
#    Updated: 2026/01/19 17:54:58 by acasper          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

NAME = so_long

CC = cc
C_FLAGS = -Wall -Wextra -Werror

LIBFT_DIR = libft
LIBFT = $(LIBFT_DIR)/libft.a

SRC_DIR = src
SRC_FILES = main.c \
	    map_parse.c \
	    map_validate.c \
	    map_path.c \
	    game_init.c \
	    game_loop.c \
	    game_render.c \
	    player_move.c \
	    textures.c \
	    utils.c \
	    error.c \
	    get_next_line.c \
	    get_next_line_utils.c

SRCS = 
OBJS = 

all: $(NAME)

$(NAME):

$(LIBFT):

%.o: %.c

clean:

fclean:

re: fclean all

.PHONY: all clean fclean re
