# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: acasper <acasper@student.42berlin.de>      +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2025/09/01 18:59:25 by acasper           #+#    #+#              #
#    Updated: 2025/09/11 20:06:08 by acasper          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

CC = cc
CFLAGS = -Wall -Werror -Wextra
RM = rm -f



all: $(SERVER) $(CLIENT)

$(SERVER):


$(CLIENT):




clean:


fclean:


re: fclean all


.PHONY: all clean fclean re

