

NAME = fractol

CC = cc
CFLAGS = -Wall -Werror -Wextra
LIBFT_PATH = include/libft
MLX_PATH = include/minilibx

SRC_DIR = src
OBJ_DIR = obj
INCLUDE_DIR = include

SRC_FILES = 
OBJ_FILES = 

LIBFT = $(LIBFT_PATH)/libft.a
MLX = $(MLX_PATH)/libmlx.a

all: $(NAME)

$(NAME): $(OBJS)


clean:
	rm -rf $(OBJDIR)

fclean: clean
	rm -f $(NAME)

re: fclean all

.PHONY: all clean fclean re

